<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bdag_team_extension"
 *
 * Auto generated by Extension Builder 2015-01-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Team Extension',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Fehmi Raqipi',
	'author_email' => 'raqipi@business-design.ch',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);